baseURL = 'https://yellatcomputers.com'
summaryLength = 20
locale = 'en-us'
title = 'I yell at computers'
theme = 'hugo-paper'

[services]
  [services.disqus]
    shortname = 'yellatcomputers'

[params]
    color = 'wheat'